package com.example.abiturientui.Mokslai.Lietuviu;

public class Klausimai {

    public static String[] autoriai = {"M. Mažvydas", "M. Daukša", "J. Radvanas", "M. K. Sarbievijus", "K. Donelaitis", "A. Mickevičius", "A. Baranauskas", "V. Kudirka", "Maironis", "J. Biliūnas", "J. Tumas-Vaižgantas", "V. Krėvė", "V. Mykolaitis-Putinas", "J.Savickis", "J. Aistis", "H. Radauskas", "S. Nėris", "B. Sruoga", "A. Škėma", "Just. Marcinkevičius", "M. Katiliškis", "J. Aputis", "S. Geda", "Šatrijos Ragana", "Vyt. Mačernis", "Br. Krivickas", "M. Martinaitis", "Č. Milošas", "J. Vaičiūnaitė", "A. Marčėnas", "J. Kunčinas", "M. Ivaškevičius", "V. Šekspyras", "J. V. Getė", "F. Kafka", "A. Kamiu"};
    /*public static String[] apibudinimai = {"M. Mažvydas", "M. Daukša", "J. Radvanas", "M. K. Sarbievijus", "K. Donelaitis", "A. Mickevičius", "A. Baranauskas", "V. Kudirka", "Maironis", "J. Biliūnas", "J. Tumas-Vaižgantas", "V. Krėvė", "V. Mykolaitis-Putinas", "J.Savickis", "J. Aistis", "H. Radauskas", "S. Nėris", "B. Sruoga", "A. Škėma", "Just. Marcinkevičius", "M. Katiliškis", "J. Aputis", "S. Geda", "Šatrijos Ragana", "Vyt. Mačernis", "Br. Krivickas", "M. Martinaitis", "Č. Milošas", "J. Vaičiūnaitė", "A. Marčėnas", "J. Kunčinas", "M. Ivaškevičius", "V. Šekspyras", "J. V. Getė", "F. Kafka", "A. Kamiu", "M. Mažvydas", "M. Daukša", "J. Radvanas", "M. K. Sarbievijus", "K. Donelaitis", "A. Mickevičius", "A. Baranauskas", "V. Kudirka", "Maironis", "J. Biliūnas", "J. Tumas-Vaižgantas", "V. Krėvė", "V. Mykolaitis-Putinas", "J.Savickis", "J. Aistis", "H. Radauskas", "S. Nėris", "B. Sruoga", "A. Škėma", "Just. Marcinkevičius", "M. Katiliškis", "J. Aputis", "S. Geda", "Šatrijos Ragana", "Vyt. Mačernis", "Br. Krivickas", "M. Martinaitis", "Č. Milošas", "J. Vaičiūnaitė", "A. Marčėnas", "J. Kunčinas", "M. Ivaškevičius", "V. Šekspyras", "J. V. Getė", "F. Kafka", "A. Kamiu"};
    public static String[] teisingi = {"M. Mažvydas", "M. Daukša", "J. Radvanas", "M. K. Sarbievijus", "K. Donelaitis", "A. Mickevičius", "A. Baranauskas", "V. Kudirka", "Maironis", "J. Biliūnas", "J. Tumas-Vaižgantas", "V. Krėvė", "V. Mykolaitis-Putinas", "J.Savickis", "J. Aistis", "H. Radauskas", "S. Nėris", "B. Sruoga", "A. Škėma", "Just. Marcinkevičius", "M. Katiliškis", "J. Aputis", "S. Geda", "Šatrijos Ragana", "Vyt. Mačernis", "Br. Krivickas", "M. Martinaitis", "Č. Milošas", "J. Vaičiūnaitė", "A. Marčėnas", "J. Kunčinas", "M. Ivaškevičius", "V. Šekspyras", "J. V. Getė", "F. Kafka", "A. Kamiu"};

     */
    public static String[] apibudinimai = {"a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b"};
    public static String[] teisingi = {"a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b"};
    public static String[] neteisingi = {"a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b", "a", "b"};

}
/*
    public static String [] autoriai = {"Kas yra Android?","Kokios operacinės sistemos pagrindu sukurta Android?","Kokia yra Android operacinės sistemos programavimo kalba","Kada buvo parduotas pirmasis Android telefonas?","Ką vaizduoja Android logotipas?"};
    public static String[] apibudinimai = {"Operacinė sistema","Kompiuterinis virusas","Linux","Windows","Paskalis","Java","2008 m. spalio mėn.","2015m. rugsėjo mėn.","Vėžliukas","Robotukas"};
    public static int[] teisingi = {0,0,1,0,1};*/